version: '3.8'

services:

  web:
    build:
       context: ./app
       dockerfile: Dockerfile
    container_name: web
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    env_file:
      - .env
    networks:
      - backend

  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  static_volume:
  media_volume:
